### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by giggio** [2020IP/TwentyTwenty.IdentityServer3.EntityFramework7#3]
I just started using your nuget package and it worked flawlessly. I did not find a way to contact you, so here it goes: thanks!
:tada:

BTW, you might want to add contact info on your readme so other people can thank you too.

**Comment by jarroda** [comment]
You're welcome, and good suggestion.  

BTW I am going to push an update in the next day or so that fixes a couple of issues I have ran across.
