### ISSUE TITLE
OperationalContext and EF7 Migration

### ISSUE THREAD

**Issue by kumoninotte** [2020IP/TwentyTwenty.IdentityServer3.EntityFramework7#4]
Would it be better to make OperationalContext to require or support sub-classing before use like ScopeConfigurationContext and ClientConfigurationContext ?

I have a trouble with EF7's Migration, it will generate migration files in the root directory the same way as main context. Sub-classing it would help as EF7 will generate migration files in sub-directory but RegisterOperationalStores doesn't support this.

Or there is a better way to handle this ?

Thanks!

**Comment by jarroda** [comment]
Does that commit look like it would provide what you're looking for? https://github.com/2020IP/TwentyTwenty.IdentityServer3.EntityFramework7/commit/f5ac987632653be99ffc2288263c460fea25ccc5

**Comment by kumoninotte** [comment]
Thanks! And Yes, it does.

Also, thanks for your work. It also gave me some inspirations!

**Comment by jarroda** [comment]
That change is merged into master and a new nuget package should be available.
