### ISSUE TITLE
Support IdentityServer4

### ISSUE THREAD

**Issue by giggio** [2020IP/TwentyTwenty.IdentityServer3.EntityFramework7#7]
I got a version working with IS4. How do you want to work with that? Should I send a PR, or are you creating a new repo? I am asking because of the name, `TwentyTwenty.IdentityServer3.EntityFramework7` won't make much sense.

**Comment by jarroda** [comment]
Yeah, the new IS4 project caught us off guard.  I think it would be useful to maintain support for EF7 in IS3, so I think the best option for us will be to create a new project altogether.  It will target coreclr and be named TwentyTwenty.IdentityServer4.EntityFramework7.  

I will create this project in a little while (today) using this repo's source.  Once its created, could you send a PR with your changes against that new repo?

**Comment by ericgreenmix** [comment]
https://github.com/2020IP/TwentyTwenty.IdentityServer4.EntityFramework7

**Comment by giggio** [comment]
Sure, I am finishing some tests and as soon as I am done I will send a PR.

**Comment by giggio** [comment]
I am almost done, there is a problem when running on .NET Full. See https://github.com/IdentityServer/IdentityServer4/issues/8. As soon as that is fixed I will send the PR.

**Comment by giggio** [comment]
Done. PR sent to https://github.com/2020IP/TwentyTwenty.IdentityServer4.EntityFramework7/pull/1.
